### PR TITLE
Update lib.js

### PR DESCRIPTION
**Pull request by johannel00**
Changed Meteor.autorun to Tracker.autorun

Meteor.autorun was depreciated in Meteor 1.7

### CODE REVIEW

**Comment by dd137** [comment]
I also had to add "tracker@1.0.3" in package.js' api.use for Tracker not to be undefined.
Edit: Ah I see you did that too in a separate pull request

**Comment by mathieustan** [comment]
Anyone can merge this branch ? :)

**Comment by ddaydd** [comment]
Thanks gwendall :)

**Comment by mathieustan** [comment]
Thanks alot !

**Pull request merged**
