### PR TITLE
Critical bug fix.

### PR DESCRIPTION
**Pull request by pavanputhra**
Fix for following issue.
https://github.com/gwendall/meteor-impersonate/issues/10

Bug fix for: Following code wasn't working

``` javascript
Impersonate.adminGroups = [
  { role: "masters", group: "group_A" },
  { role: "bosses", group: "group_B" }
];
```

### CODE REVIEW

**Comment by Siyfion** [comment]
@gwendall Can we get this merged as it fixes quite a crucial bug for many??

**Comment by rmuratov** [comment]
So due to user in this commit isn't updated with `_impersonateToken` fields still we need to [reset](https://github.com/pavanputhra/meteor-impersonate/blob/master/server/lib.js#L6-L12) it?

**Comment by onedr0p** [comment]
+1 where are you @gwendall.

Sorry if I sound rude but this seems to be a common theme with developers: create a neat package and then never respond to simple PRs or just completely leave the project like we've seen here. I wish more people would let others be collaborators on their repos... We are a hive-mind, no?

I will just use @pavanputhra fork and implement into my site _natively_. Thanks for the fix!

**Comment by pavanputhra** [comment]
@rmuratov 
I think `_impersonateToken` was being used in previous version of package. So, for users who are updating package form previous version, the code tries to clean up the db.

It's just a guess by looking at few codes, back in history. I may be wrong.

**Comment by gwendall** [comment]
Done. Sorry all for the late merge, I had to take a leave from coding for personal reasons those past months. Enjoy!

**Comment by onedr0p** [comment]
Thanks @gwandall sorry for sounding like a dick, but I see this a trend in 3rd party packages for meteor.

**Pull request merged**
